dataset: 'Avazu'
batch_size: 1024
split: ['0.8','0.1','0.1']
early_stop: 10
verbose: True
draw_loss_points: 100

teacher: 'CIN'
model: 'KD_DAGFM'
phase: 'teacher_training'
type: 'inner'
embedding_size: 16
lr: 1e-4         
L2: 1e-5
t_cin: [200,200,200]
depth: 3
alpha: 0.1
beta: 921.6