dataset: 'Criteo'
batch_size: 1024
split: ['0.8','0.1','0.1']
early_stop: 10
verbose: True
draw_loss_points: 100

teacher: 'CrossNet'
model: 'KD_DAGFM'
phase: 'teacher_training'
type: 'outer'
embedding_size: 16
lr: 1e-4             
L2: 1e-5
t_depth: 3
depth: 3
alpha: 0.1
beta: 921.6