dataset: 'Movie'
batch_size: 1024
split: ['0.8','0.1','0.1']
early_stop: 3
verbose: True
draw_loss_points: 100

teacher: 'CrossNet'
model: 'KD_DAGFM'
phase: 'teacher_training'
type: 'outer'               # 0.003, 1e-6      0.003 0      0.0001 0.00001        100%数据
embedding_size: 16
lr: 0.003
L2: 0.000001
t_depth: 3
depth: 3
alpha: 0.1
beta: 921.6

#8902 3248   8928 3205